import demo_mdet
import torch
demo_mdet.DEVICE = torch.device('cuda:1')
if __name__ == '__main__':
    pass
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge5/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge6/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge7/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge8/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge9/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge10/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8n/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8s/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8m/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8l/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8x/weights/best.pt')
    #
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10n/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10s/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10m/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10b/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10l/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x/weights/best.pt')
    #
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9e/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m4/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m1/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m12/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m13/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m14/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m15/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m16/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m17/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m18/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m19/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m110/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m111/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m112/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m113/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m114/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m115/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m116/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m117/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m118/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m119/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m120/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m121/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m122/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m32/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m33/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m34/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m35/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m36/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m37/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m38/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m39/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m310/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m311/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m312/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m313/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m314/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m315/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m316/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m317/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m318/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m319/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m320/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m321/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m322/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm5/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm6/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm7/weights/best.pt')

    demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm/weights/best.pt')
    demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm2/weights/best.pt')
    demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm3/weights/best.pt')
    demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm4/weights/best.pt')
    demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm5/weights/best.pt')