import demo_mdet
import torch
demo_mdet.DEVICE = torch.device('cuda:1')
if __name__ == '__main__':
    pass
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge5/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge6/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge7/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge8/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge9/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_mloss_enlarge10/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8n/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8s/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8m/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8l/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo8x/weights/best.pt')
    #
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10n/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10s/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10m/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10b/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10l/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x/weights/best.pt')
    #
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9e/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9s4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9c4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo9m4/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m1/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m12/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m13/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m14/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m15/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m16/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m17/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m18/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m19/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m110/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m111/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m112/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m113/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m114/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m115/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m116/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m117/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m118/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m119/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m120/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m121/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m122/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m32/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m33/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m34/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m35/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m36/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m37/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m38/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m39/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m310/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m311/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m312/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m313/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m314/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m315/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m316/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m317/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m318/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m319/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m320/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m321/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_m322/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm5/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm6/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mm7/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm5/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm6/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm7/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm8/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm9/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm10/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm11/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm13/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm14/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm15/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm16/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm17/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm18/weights/best.pt')



    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head5/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head6/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head7/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head8/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head9/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head10/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head11/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head12/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head13/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head14/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head15/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head16/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head17/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head18/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head19/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head20/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head21/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head22/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head23/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head24/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head25/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head26/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head27/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head28/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head29/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head40/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head41/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head32/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head33/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head34/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head35/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head36/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head37/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head38/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head39/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head40/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head41/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head42/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head43/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head44/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head45/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head46/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head47/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head48/weights/best.pt')



    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt')
    # demo_mdet.model_gat_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt',
    #     com_path='/nfsv4/23039356r/data/billboard/data0806_m/yolo_rgb_detection5_10_c/co_occurrence_matrix1.csv'
    # )
    # demo_mdet.model_gat_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt',
    #     com_path='/nfsv4/23039356r/data/billboard/data0806_m/yolo_rgb_detection5_10_c/co_occurrence_matrix2.csv'
    # )
    # demo_mdet.model_gat_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt',
    #     com_path='/nfsv4/23039356r/data/billboard/data0806_m/yolo_rgb_detection5_10_c/co_occurrence_matrix3.csv'
    # )
    # demo_mdet.model_gat_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt',
    #     com_path='/nfsv4/23039356r/data/billboard/data0806_m/yolo_rgb_detection5_10_c/co_occurrence_matrix4.csv'
    # )
    # demo_mdet.model_gat_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt',
    #     com_path='/nfsv4/23039356r/data/billboard/data0806_m/yolo_rgb_detection5_10_c/co_occurrence_matrix5.csv'
    # )
    # demo_mdet.model_gat_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt',
    #     com_path='/nfsv4/23039356r/data/billboard/data0806_m/yolo_rgb_detection5_10_c/co_occurrence_matrix6.csv'
    # )




    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc2/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc3/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc5/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc6/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc7/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc8/weights/best.pt')

    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_mmm12/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc4/weights/best.pt')
    # demo_mdet.model_val(weight_path=r'runs/mdetect/exp_yolo10x_head_mc7/weights/best.pt')
